### ISSUE TITLE
网站是不是挂了？访问不了

### ISSUE THREAD

**Issue by chaohui997** [ixiaoyang8/iodraw#17]
网站是不是挂了？访问不了

**Comment by YgluWanh** [comment]
是的，咋整啊

**Comment by ixiaoyang8** [comment]
云服务器出现了问题，正在和平台积极沟通中

**Comment by leonschat** [comment]
终于找到解决办法了，昨天就发现不行了，自己的学习笔记全在这里面，马上准备考试了，这突然打不开人都麻了

**Comment by wufe8** [comment]
暂时下个本地版用着了 感谢开发团队的贡献 有什么资金情况的话可以提出捐助通道

**Comment by ixiaoyang8** [comment]
由于云厂商出现故障，造成10月7日~10月23日的数据丢失，在此期间充会员的用户可将订单号和用户名发送邮件至ixiaoyang8@qq.com，管理员将进行手工补单；此外，系统已统一对过期日在10月23日之后的会员进行了7天的补偿，可在我的账号里查看；涉及到AI部分的功能尚在修复中，对您造成的不便深感抱歉！

**Comment by ixiaoyang8** [comment]
网站已恢复正常
