### ISSUE TITLE
外部打开iodraw文件导致缓存的项目被全部清空

### ISSUE THREAD

**Issue by Kirinni** [ixiaoyang8/iodraw#19]
画完图之后想着打开保存在我文件夹里的iodraw文件看看有没有问题，选择iodraw文件用iodraw打开后，软件内的项目全部被清空了，列表上全是undefined，画的图也因为没有连接网络而未同步到github。
发现项目全都消失后，不知道程序是将文件缓存在何处的，只好下载GitHub的版本，但进度差距有点大，我就想着再打开我存在本地的文件，这次从软件内导入，成功打开了项目，但这是一个比GitHub版本更落后的版本，于是我只好换回GitHub版本重复之前的工作，结果发现本地的文件覆盖了Github上的版本，还好有历史记录，不然真的全都完了，不过今天（昨天）做的确实全都完了。
不奢求能够修复从外部打开项目文件导致项目全都消失的问题，至少能够添加选择缓存文件路径的功能或者显示程序所用的缓存文件夹，我想我之前画的图的缓存可能还在硬盘的哪个地方躺着吧，但是我再也找不到它了。

**Comment by ixiaoyang8** [comment]
v3.3.1已经支持将文件保存到本地磁盘了，右上角点击设置 -> 保存位置, 可以修改默认保存路径
