### ISSUE TITLE
甘特图保存后打开，开始时间自动变成了今天

### ISSUE THREAD

**Issue by qq-jl** [ixiaoyang8/iodraw#4]
每次打开甘特图，开始时间会自动变成明天
![企业微信截图_20220119180853](https://user-images.githubusercontent.com/47658921/150109523-af93cfef-c005-44c4-b72a-df04f875b893.png)
。比如2022-02-10 保存后，打开变成了 2022-01-20

**Comment by ixiaoyang8** [comment]
已修复，请保存文件后清除浏览器缓存重试
