### ISSUE TITLE
甘特图-导出png-bar chart部分错乱

### ISSUE THREAD

**Issue by pheman** [ixiaoyang8/iodraw#7]
如果任务较多，导出png以后，会引发错乱，如图
![智能合规尽调 (4)](https://user-images.githubusercontent.com/14324098/173715539-5ff3e2d3-32b8-4d0a-aed7-ea135edd2aab.png)
重现该问题，请使用下面的gantt文件(删除txt后缀即可)
[智能合规尽调 (3).gantt.txt](https://github.com/ixiaoyang8/iodraw/files/8904884/3.gantt.txt)

**Comment by ixiaoyang8** [comment]
已修改
